## 딥러닝기초분류 

In [42]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, random_split, DataLoader

In [43]:
device = 'cpu'
if torch.cuda.is_available():
    device = 'cuda'

In [44]:
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [45]:
df = pd.read_csv('iris.csv')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [46]:
X = df.iloc[:,:-1].values

In [47]:
y = df.iloc[:, -1].values

In [48]:
type(df.iloc[:, :-1])

pandas.core.frame.DataFrame

In [49]:
X = torch.tensor(X, dtype=torch.float32).to(device)
y = torch.tensor(y, dtype=torch.long).to(device)

In [50]:
dataset = TensorDataset(X, y)

In [51]:
n = len(dataset)
ratio_tn = 0.8
n_tn = int(n*ratio_tn)
n_te = n - n_tn

In [52]:
print("전체 데이터 개수: ", n)
print("트레이닝 데이터 비율: ", ratio_tn)
print("트레이닝 데이터 개수: ", n_tn)
print("테스트 데이터 개수: ", n_te)

전체 데이터 개수:  150
트레이닝 데이터 비율:  0.8
트레이닝 데이터 개수:  120
테스트 데이터 개수:  30


In [22]:
dataset = TensorDataset(X, y)

In [24]:
for i in range(0, 10):
    print(dataset[i])

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))


In [25]:
train_data, test_data = random_split(dataset, [n_tn, n_te])

In [26]:
for i in range(0, 3):
    feature, target = train_data[i]
    print("Feature: ", feature)
    print("Target: ", target)
    print()

Feature:  tensor([5.0000, 3.2000, 1.2000, 0.2000])
Target:  tensor(0)

Feature:  tensor([7.3000, 2.9000, 6.3000, 1.8000])
Target:  tensor(2)

Feature:  tensor([7.2000, 3.0000, 5.8000, 1.6000])
Target:  tensor(2)



In [27]:
n_batch = 16
train_loader = DataLoader(train_data, batch_size=n_batch, shuffle=True)

In [30]:
batch_count = 0
for minibatch in train_loader:
    features, targets = minibatch
    print("Features: ", features)
    print("Target: ", targets)
    print()
    batch_count += 1
    if batch_count >= 2:
        break

Features:  tensor([[6.7000, 3.1000, 5.6000, 2.4000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [6.9000, 3.1000, 4.9000, 1.5000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [4.7000, 3.2000, 1.6000, 0.2000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [6.2000, 3.4000, 5.4000, 2.3000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [6.5000, 3.0000, 5.8000, 2.2000]])
Target:  tensor([2, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 0, 1, 0, 2])

Features:  tensor([[6.3000, 2.8000, 5.1000, 1.5000],
        [4.9000, 3.6000, 1.4000, 0.1000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [5.8000, 2.6000, 4.0000, 1.2000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [7.7000, 2.8000, 6.7

In [33]:
# hyperparameters
learning_rate = 0.01
epochs = 1000
n_feature = len(train_data[0][0])
print(n_feature)

4


In [34]:
class Classifier(nn.Module):
    def __init__(self, n_feature):
        super().__init__()
        self.fc1 = nn.Linear(n_feature, 10)
        self.leakyrelu = nn.LeakyReLU()
        self.fc2 = nn.Linear(10, 3)

    def forward(self, x):
        x = self.fc1(x)
        x = self.leakyrelu(x)
        x = self.fc2(x)

        return x

In [35]:
model = Classifier(n_feature).to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

In [38]:
total_batch = len(train_loader)
model.train()
for epoch in range(epochs):
    avg_cost = 0
    for X_tn, y_tn in train_loader:

        X_tn = X_tn.to(device)
        y_tn = y_tn.to(device)

        optimizer.zero_grad()
        y_hat = model.forward(X_tn)
        cost = criterion(y_hat, y_tn)
        cost.backward()
        optimizer.step()

        avg_cost += cost/total_batch

    if (epoch+1) % 100 == 0:
        print('Epoch [%d/%d], Cost: %.4f' % (epoch+1, epochs, avg_cost))

C:\Users\이세희\AppData\Local\Temp\ipykernel_28472\2012644166.py:19: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\autograd\generated\python_variable_methods.cpp:837.)
  print('Epoch [%d/%d], Cost: %.4f' % (epoch+1, epochs, avg_cost))


Epoch [100/1000], Cost: 0.2322
Epoch [200/1000], Cost: 0.1323
Epoch [300/1000], Cost: 0.1046
Epoch [400/1000], Cost: 0.0880
Epoch [500/1000], Cost: 0.0967
Epoch [600/1000], Cost: 0.0810
Epoch [700/1000], Cost: 0.1021
Epoch [800/1000], Cost: 0.0763
Epoch [900/1000], Cost: 0.0705
Epoch [1000/1000], Cost: 0.0701


In [41]:
X_te = []
y_te = []

for row in test_data:
    feature, target = row
    X_te.append(feature)
    y_te.append(target)

In [57]:
X_te = torch.stack(X_te)
y_te = torch.stack(y_te)

In [59]:
model.eval()
with torch.no_grad():
    prediction = model.forward(X_te)
    correct_prediction = torch.argmax(prediction, 1) == y_te
    accuracy = correct_prediction.float().mean()
    print("accuracy: ", accuracy.item())

accuracy:  1.0


In [60]:
y_te

tensor([2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2,
        0, 0, 0, 2, 0, 0])

In [62]:
torch.argmax(prediction, 1)

tensor([2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2,
        0, 0, 0, 2, 0, 0])