## 딥러닝 기초 

- 코드만 보고 그림 그리는 연습 

In [1]:
import numpy as np

# 입력층
input_data = np.array([[2,3], [5,1]])
print(input_data)
x = input_data.reshape(-1)
print(x)

[[2 3]
 [5 1]]
[2 3 5 1]


In [2]:
# 가중치 및 편향
w1 = np.array([2, 1, -3, 3])
w2 = np.array([1, -3, 1, 3])
b1 = 3
b2 = 3

In [5]:
# 가중합
W = np.array([w1, w2])
print(W)

b = np.array([b1, b2])
print(b)

weight_sum = np.dot(W, x) + b
print(weight_sum)

[[ 2  1 -3  3]
 [ 1 -3  1  3]]
[3 3]
[-2  4]


In [6]:
# 출력층
res = 1/(1+np.exp(-weight_sum))
print(res)

[0.11920292 0.98201379]
