## 파이토치를 활용한 분류 

In [1]:
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, random_split, DataLoader

In [2]:
device = 'cpu'
if torch.cuda.is_available():
    device = 'cuda'

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
df = pd.read_csv('iris.csv')

In [4]:
df

,sepal_length,sepal_width,petal_length,petal_width,class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
X[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [8]:
type(df.iloc[:, :-1])

pandas.core.frame.DataFrame

In [9]:
type(df.iloc[:, :-1].values)

numpy.ndarray

In [10]:
X = torch.tensor(X, dtype=torch.float32).to(device)
y = torch.tensor(y, dtype=torch.long).to(device)

In [11]:
X[0:10]

tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [4.9000, 3.1000, 1.5000, 0.1000]])

In [12]:
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

In [13]:
dataset = TensorDataset(X, y)

In [14]:
dataset[0:10]

(tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [15]:
for i in range(0, 10):
    print(dataset[i])

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))


In [16]:
n = len(dataset)
ratio_tn = 0.8
n_tn = int(n*ratio_tn)
n_te = n - n_tn

In [17]:
print("전체 데이터 개수: ", n)
print("트레이닝 데이터 비율: ", ratio_tn)
print("트레이닝 데이터 개수: ", n_tn)
print("테스트 데이터 개수: ", n_te)

전체 데이터 개수:  150
트레이닝 데이터 비율:  0.8
트레이닝 데이터 개수:  120
테스트 데이터 개수:  30


In [18]:
train_data, test_data = random_split(dataset, [n_tn, n_te])

In [19]:
for i in range(0, 3):
    feature, target = train_data[i]
    print("Feature: ", feature)
    print("Target: ", target)
    print()
    

Feature:  tensor([5.0000, 3.2000, 1.2000, 0.2000])
Target:  tensor(0)

Feature:  tensor([7.3000, 2.9000, 6.3000, 1.8000])
Target:  tensor(2)

Feature:  tensor([7.2000, 3.0000, 5.8000, 1.6000])
Target:  tensor(2)



In [20]:
n_batch = 16
train_loader = DataLoader(train_data, batch_size=n_batch, shuffle=True)

In [21]:
batch_count=0
for minibatch in train_loader:
    features, targets = minibatch
    print("Feature: ", features)
    print("Target: ", targets)
    print()

    batch_count += 1
    if batch_count >= 2:
        break

Feature:  tensor([[5.1000, 3.4000, 1.5000, 0.2000],
        [6.4000, 2.9000, 4.3000, 1.3000],
        [7.2000, 3.0000, 5.8000, 1.6000],
        [6.3000, 3.3000, 6.0000, 2.5000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [6.7000, 3.1000, 4.4000, 1.4000],
        [5.5000, 2.5000, 4.0000, 1.3000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [6.4000, 2.7000, 5.3000, 1.9000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [5.5000, 2.6000, 4.4000, 1.2000]])
Target:  tensor([0, 1, 2, 2, 2, 1, 1, 1, 0, 2, 2, 0, 0, 2, 2, 1])

Feature:  tensor([[5.8000, 2.7000, 3.9000, 1.2000],
        [4.9000, 3.1000, 1.5000, 0.2000],
        [4.7000, 3.2000, 1.6000, 0.2000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [7.3000, 2.9000, 6.300

In [22]:
# hypermarameters
learning_rate = 0.01
epochs = 1000
n_feature = len(train_data[0][0])
print(n_feature)

4


In [23]:
class Classifier(nn.Module):
    def __init__(self, n_feature):
        super().__init__()
        self.fc1 = nn.Linear(n_feature, 10)  # 4(feature개수) -> 10
        self.leakyrelu = nn.LeakyReLU()  # 활성화 함수 
        self.fc2 = nn.Linear(10, 3)  # 10 -> 3(클래스개수)

    def forward(self, x):
        x = self.fc1(x)
        x = self.leakyrelu(x)
        x = self.fc2(x)

        return x

In [24]:
model = Classifier(n_feature).to(device)

In [25]:
criterion = nn.CrossEntropyLoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

In [26]:
total_batch = len(train_loader)
model.train()

for epoch in range(epochs):
    avg_cost = 0
    for X_tn, y_tn in train_loader:

        X_tn = X_tn.to(device)
        y_tn = y_tn.to(device)
        
        optimizer.zero_grad()
        y_hat = model.forward(X_tn)
        cost = criterion(y_hat, y_tn)
        cost.backward()
        optimizer.step()

        avg_cost += cost/total_batch

    if (epoch+1)%100 == 0:
        print('Epoch [%d/%d], Cost: %.4f' % (epoch+1, epochs, avg_cost))

C:\Users\User\AppData\Local\Temp\ipykernel_760\2873317124.py:20: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\autograd\generated\python_variable_methods.cpp:837.)
  print('Epoch [%d/%d], Cost: %.4f' % (epoch+1, epochs, avg_cost))


Epoch [100/1000], Cost: 0.2826
Epoch [200/1000], Cost: 0.1438
Epoch [300/1000], Cost: 0.1313
Epoch [400/1000], Cost: 0.0989
Epoch [500/1000], Cost: 0.0925
Epoch [600/1000], Cost: 0.0843
Epoch [700/1000], Cost: 0.0785
Epoch [800/1000], Cost: 0.0743
Epoch [900/1000], Cost: 0.0992
Epoch [1000/1000], Cost: 0.0784


In [27]:
y_hat

tensor([[-11.8435,   2.2322,   9.3875],
        [ -8.5642,   4.1462,   5.0239],
        [ -9.4227,   2.6434,   6.8071],
        [ -1.4509,   4.6262,  -2.0076],
        [ -1.0946,   4.8308,  -2.5748],
        [ 13.7059,   7.9695, -19.0682],
        [-11.3740,   2.9375,   8.4218],
        [ -4.2067,   3.6314,   1.2740]], grad_fn=<AddmmBackward0>)

In [28]:
y_hat.shape

torch.Size([8, 3])

In [29]:
y_tn

tensor([2, 2, 2, 1, 1, 0, 2, 1])

In [30]:
X_te = []
y_te = []

for row in test_data:
    feature, target = row
    X_te.append(feature)
    y_te.append(target)

In [31]:
X_te = torch.stack(X_te)
y_te = torch.stack(y_te)

In [32]:
# print(X_te)
# print(y_te)

In [33]:
model.eval()
with torch.no_grad():
    prediction = model.forward(X_te)
    correct_prediction = torch.argmax(prediction, 1) == y_te
    accuracy = correct_prediction.float().mean()
    print("Accuracy: ", accuracy.item())

Accuracy:  0.9666666388511658


In [34]:
y_te

tensor([2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2,
        0, 0, 0, 2, 0, 0])

In [35]:
torch.argmax(prediction, 1)

tensor([2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2,
        0, 0, 0, 2, 0, 0])

In [36]:
PATH = './iris_model01.pt'
torch.save(model.state_dict(), PATH)

In [37]:
PATH = './iris_model01.pt'

# load the saved model
loaded_model = Classifier(n_feature).to(device)
loaded_model.load_state_dict(torch.load(PATH))

<All keys matched successfully>

In [38]:
loaded_model.eval()
with torch.no_grad():
    prediction = loaded_model(X_te)
    correct_prediction = torch.argmax(prediction, 1) == y_te
    accuracy = correct_prediction.float().mean()
    print('Accuracy: ', accuracy.item())

Accuracy:  0.9666666388511658
